const CHANNEL = `uptapgame`;
export const API_URL = `https://uptapapi.uptap.com/h5Game/?type=GameList&platform=uptap&token=dXB0YXBnYW1l572R56uZ55So`; //游戏源
// export const GAME_PATH = `https://cdn.uptapgame.com/newgames/minigame.html?platform=uptap&appid=`; //渠道游戏路径
export const GAME_PATH = `https://cdn.uptapgame.com/newgames/minigame.html?platform=${CHANNEL}&appid=`; //渠道游戏路径 //2022.06.16 因证书到期，删除https
export const IMAGE_FORMAT = `png`;
export const IMAGE_PATH = `https://cdn.iwantalipstick.com/gameicon2/${IMAGE_FORMAT}/`;

export const SITE_META = {
  name: `UpTapGame`,
  url: `https://www.uptapgame.com/`,
  domain: `uptapgame.com`,
};

export const MODE = `dev`;

export const SITE_NAME = `UpTapGame`; //网站名称
export const SITE_URL = `https://www.uptapgame.com/`; //网站地址

export const GA_ID = `G-L2E7FV0F5M`; //Google Analytics ID
export const ADSENSE_ID = `ca-pub-4975852181579567`; //Google Adsense ID
// export const ADSENSE_ID = `ca-pub-9209477879340784`; //Google Adsense ID

export const ADS_SLOTS_ID = {
  home: `3630570624`,
  categorgy: `2034132514`,
  detail: `9812835592`,
};

export const SELECTED_GAMES = []; //选择游戏
export const EXCLUED_GAMES = [
  // "MagicBomb",
  // "IceEscape",
  // "HumanTower",
  // "HamsterRun",
  // "BestShooter",
  // "AttackHero",
  // "MagicCarpenter",
  // "4096",
  // "BraveArcher",
  // "ColorHammer",
  // "CrayonPop",
  // "CutMaster",
  // "ShootingStar",
  // "Woodisland",
  // "TinyWar",
  // "InfiDefense",
  // "BoomingPlant",
  // "BestSniper",
  // "SkatingMaster",
  // "RushAndFire",
  // "BigEater",
  // "LittleFarm",
  // "Hurricane",
  "HouseLink",
]; //排除游戏
export const FEATURED_GAMES = ["FireTheGun", "CrazyKnife", "CrazyMoto"]; //设置推荐游戏
export const LANDSCAPE_GAMES = [`CrazyGunfight`];

export const RE_CATEGORY = [
  {
    Shooting: [
      "FruitMonster",
      "BestSniper",
      "AirBrawl",
      "CrackShot",
      "FingerCannon",
      "BulletMan",
      "SplittingCells",
      "MrBullet",
      "MergeGuns3D",
      "ShootingCubes",
      "KnockSmash",
      "GunShooter",
      "BulletMaster3D",
      "FireTheGun",
      "ArchersKing",
      "KillAllZombies",
      "SuperArcher",
      "ArcheryKing",
      "BestShooter",
      "BlockGun3D",
      "KnockBalls",
    ],
  },
  {
    Adventure: [
      "CrazyConveyor",
      "WildRoll",
      "GlidingCharger",
      "PuzzleVenture",
      "FrozenMagic",
      "Mining",
      "MiningMaster",
      "DeathRun",
      "CleverStrut",
      "DeathJump",
      "ZombieSurvival",
      "StickmanVsZombies",
      "BraveArcher",
      "RollingAgent",
      "SausageRun",
      "AttackHero",
    ],
  },
  {
    Strategy: [
      "SuperCells",
      "MagicPaint",
      "ColorSplash",
      "TinyWar",
      "VirusWar",
      "TrappedPirate",
      "OpenFire",
      "BombingTime",
      "FisherMan",
      "MyTerritory",
      "InfiDefense",
      "PlantBeatZombies",
      "CrazyBomb",
      "KimbapRun",
      "SuperDefense",
      "TowerDefenseX",
      "MergeAndDefense",
      "DefenseTower",
      "MagicBomb",
    ],
  },
  {
    Puzzle: [
      "MadEraser",
      "FreeFall",
      "FruitsFall",
      "MagicPainter",
      "FeedMaster",
      "AmazingRoad",
      "PianoKeys",
      "HouseLink",
      "GravityBowling",
      "MyHome",
      "MagicWorm",
      "HelpTheSheep",
      "RollingBall",
      "MagicDraw",
      "HelpTheFish",
      "TrainIsComing",
      "SpinTheMaze",
      "CutMaster",
      "CountingMaster",
      "CleverRescue",
      "PouringBall",
      "EasyCharger",
      "BlockMaster",
      "TheSameWorld",
      "ColorBead",
      "HappyTetris",
      "BlockMaze",
      "BrainMaster",
      "ColorRing",
      "Super2048",
      "PipePuzzle",
      "FairyTalesPuzzle",
      "MagicJigsaw",
      "MagicNumber",
      "FillTheGlass",
      "PandaRescue",
      "BlockPuzzle",
      "SolitaireClassic",
      "4096",
      "HappyBilliards",
      "AnipopLink",
      "CollectColorfulBalls",
      "CopyLaser",
      "SuperCoaster",
      "CrazyPortal",
      "Transform",
      "HelpTheZombie",
    ],
  },
  {
    Sports: [
      "SuperSoccer",
      "ShootingStar",
      "BilliardKing",
      "BallIsComing",
      "BatterKing",
      "DartsKing3D",
      "PowerShooter",
      "GoldenBoot",
      "RocketJump",
      "8BallKing",
      "Chess3D",
      "MyBowling3D",
      "AirHockey3D",
      "SuperGolf",
      "AceMan",
      "TableTennisChampionship",
      "SoccerHero",
      "ArcheryMaster",
      "GoldenGlove",
    ],
  },
  {
    Arcade: [
      "CleverJump",
      "BigEater",
      "CrayonPop",
      "BuilderRun",
      "AntRun",
      "SnakeGo",
      "SharkIsComing",
      "BubblePop",
      "JumpSmash",
      "TrafficRun",
      "TrafficPassing",
      "HiTaxi",
      "BoardTheTrain",
      "TwistyRoad",
      "MagicDonuts",
      "CrashTower3D",
      "FlyPass",
      "NoneLess",
      "CrazyJump",
      "FutureWarrior",
      "DigEscape",
      "ColorHammer",
      "RushingRover",
      "FierceCity",
      "PuppyRun",
      "PenguinDash",
      "MonsterCrash",
      "FinalBattle",
      "CrazyRace",
      "HungyBunny",
      "HungryMonster",
      "JumpingMonkey",
      "HungryAnimals",
      "CrazyTrain3D",
      "BigSword",
      "RushAndFire",
      "SnakeHit",
      "IronAttack",
      "BattleBurger",
      "HumanTower",
      "HamsterRun",
    ],
  },
  {
    Racing: [
      "RoofRunner",
      "CityExpress",
      "MagicParkour",
      "SkyRunning3D",
      "RoadCharger",
      "MrRacer",
      "FeverRacing",
      "CrazyMoto",
      "SwiftRider",
      "UltraDrift",
      "CrazyDrift",
      "CrazyKart3D",
      "HillRacing",
      "ColorBall3D",
      "SkatingMaster",
      "IceEscape",
    ],
  },
  {
    "Match 3": [
      "ColorCrash",
      "RainbowSplash",
      "MatchingCook",
      "MelodyLink",
      "BubbleBlast",
      "MahjongLink",
      "MergeMagicJewellery",
      "MahjongLink3D",
      "ZumaMarbles",
      "ZooBlast",
      "DragonCrush",
      "MahjongConnect",
      "PetsMatch",
      "BounceShooter",
      "TowerBlast3D",
      "BumbleShooter",
      "DessertConnect",
    ],
  },
  {
    Casual: [
      "NastyBomb",
      "DashCat",
      "CrazyKnife",
      "CandyHit",
      "ShootSmash",
      "PetRun",
      "LetMeIn",
      "MagicCarpenter",
      "SaveThePets",
      "SuperThrow",
    ],
  },
  {
    Simulation: [
      "HarvestStory",
      "MergeCat",
      "RelivedLife",
      "IdleRestaurantTycoon",
      "WoodIsland",
      "BoomingPlant",
      "ImEmpire",
      "MyCat",
      "IslandSurvival",
      "LittleMiner",
      "LittleFarm",
      "SuperMiner",
    ],
  },
  {
    Girl: ["MyUnicorn", "MyBabyCare", "DressQueen", "LostInLust"],
  },
  {
    IO: [
      "FuryEdge",
      "CrazyHammer",
      "MergeKill",
      "CrazyGunfight",
      "Knife",
      "Hurricane",
    ],
  },
];
